export const twDistrict =
    [
        {
            city: '基隆市',
            contain: [
                { zip: '200', county: '仁愛區' },
                { zip: '201', county: '信義區' },
                { zip: '202', county: '中正區' },
                { zip: '203', county: '中山區' },
                { zip: '204', county: '安樂區' },
                { zip: '205', county: '暖暖區' },
                { zip: '206', county: '七堵區' }
            ]
        },
        {
            city: '臺北市',
            contain: [
                { zip: '100', county: '中正區' },
                { zip: '103', county: '大同區' },
                { zip: '104', county: '中山區' },
                { zip: '105', county: '松山區' },
                { zip: '106', county: '大安區' },
                { zip: '108', county: '萬華區' },
                { zip: '110', county: '信義區' },
                { zip: '111', county: '士林區' },
                { zip: '112', county: '北投區' },
                { zip: '114', county: '內湖區' },
                { zip: '115', county: '南港區' },
                { zip: '116', county: '文山區' }
            ]
        },
        {
            city: '新北市',
            contain: [
                { zip: '207', county: '萬里區' },
                { zip: '208', county: '金山區' },
                { zip: '220', county: '板橋區' },
                { zip: '221', county: '汐止區' },
                { zip: '222', county: '深坑區' },
                { zip: '223', county: '石碇區' },
                { zip: '224', county: '瑞芳區' },
                { zip: '226', county: '平溪區' },
                { zip: '227', county: '雙溪區' },
                { zip: '228', county: '貢寮區' },
                { zip: '231', county: '新店區' },
                { zip: '232', county: '坪林區' },
                { zip: '233', county: '烏來區' },
                { zip: '234', county: '永和區' },
                { zip: '235', county: '中和區' },
                { zip: '236', county: '土城區' },
                { zip: '237', county: '三峽區' },
                { zip: '238', county: '樹林區' },
                { zip: '239', county: '鶯歌區' },
                { zip: '241', county: '三重區' },
                { zip: '242', county: '新莊區' },
                { zip: '243', county: '泰山區' },
                { zip: '244', county: '林口區' },
                { zip: '247', county: '蘆洲區' },
                { zip: '248', county: '五股區' },
                { zip: '249', county: '八里區' },
                { zip: '251', county: '淡水區' },
                { zip: '252', county: '三芝區' },
                { zip: '253', county: '石門區' }
            ]
        },
        {
            city: '桃園市',
            contain: [
                { zip: '320', county: '中壢區' },
                { zip: '324', county: '平鎮區' },
                { zip: '325', county: '龍潭區' },
                { zip: '326', county: '楊梅區' },
                { zip: '327', county: '新屋區' },
                { zip: '328', county: '觀音區' },
                { zip: '330', county: '桃園區' },
                { zip: '333', county: '龜山區' },
                { zip: '334', county: '八德區' },
                { zip: '335', county: '大溪區' },
                { zip: '336', county: '復興區' },
                { zip: '337', county: '大園區' },
                { zip: '338', county: '蘆竹區' }
            ]
        },
        {
            city: '新竹市',
            contain: [
                { zip: '300', county: '東區' },
                { zip: '300', county: '北區' },
                { zip: '300', county: '香山區' }
            ]
        },
        {
            city: '新竹縣',
            contain: [
                { zip: '302', county: '竹北市' },
                { zip: '303', county: '湖口鄉' },
                { zip: '304', county: '新豐鄉' },
                { zip: '305', county: '新埔鎮' },
                { zip: '306', county: '關西鎮' },
                { zip: '307', county: '芎林鄉' },
                { zip: '308', county: '寶山鄉' },
                { zip: '310', county: '竹東鎮' },
                { zip: '311', county: '五峰鄉' },
                { zip: '312', county: '橫山鄉' },
                { zip: '313', county: '尖石鄉' },
                { zip: '314', county: '北埔鄉' },
                { zip: '315', county: '峨眉鄉' }
            ]
        },
        {
            city: '苗栗縣',
            contain: [
                { zip: '350', county: '竹南鎮' },
                { zip: '351', county: '頭份鎮' },
                { zip: '352', county: '三灣鄉' },
                { zip: '353', county: '南庄鄉' },
                { zip: '354', county: '獅潭鄉' },
                { zip: '356', county: '後龍鎮' },
                { zip: '357', county: '通霄鎮' },
                { zip: '358', county: '苑裡鎮' },
                { zip: '360', county: '苗栗市' },
                { zip: '361', county: '造橋鄉' },
                { zip: '362', county: '頭屋鄉' },
                { zip: '363', county: '公館鄉' },
                { zip: '364', county: '大湖鄉' },
                { zip: '365', county: '泰安鄉' },
                { zip: '366', county: '銅鑼鄉' },
                { zip: '367', county: '三義鄉' },
                { zip: '368', county: '西湖鄉' },
                { zip: '369', county: '卓蘭鎮' }
            ]
        },
        {
            city: '臺中市',
            contain: [
                { zip: '400', county: '中區' },
                { zip: '401', county: '東區' },
                { zip: '402', county: '南區' },
                { zip: '403', county: '西區' },
                { zip: '404', county: '北區' },
                { zip: '406', county: '北屯區' },
                { zip: '407', county: '西屯區' },
                { zip: '408', county: '南屯區' },
                { zip: '411', county: '太平區' },
                { zip: '412', county: '大里區' },
                { zip: '413', county: '霧峰區' },
                { zip: '414', county: '烏日區' },
                { zip: '420', county: '豐原區' },
                { zip: '421', county: '后里區' },
                { zip: '422', county: '石岡區' },
                { zip: '423', county: '東勢區' },
                { zip: '424', county: '和平區' },
                { zip: '426', county: '新社區' },
                { zip: '427', county: '潭子區' },
                { zip: '428', county: '大雅區' },
                { zip: '429', county: '神岡區' },
                { zip: '432', county: '大肚區' },
                { zip: '433', county: '沙鹿區' },
                { zip: '434', county: '龍井區' },
                { zip: '435', county: '梧棲區' },
                { zip: '436', county: '清水區' },
                { zip: '437', county: '大甲區' },
                { zip: '438', county: '外埔區' },
                { zip: '439', county: '大安區' }
            ]
        },
        {
            city: '彰化縣',
            contain: [
                { zip: '500', county: '彰化市' },
                { zip: '502', county: '芬園鄉' },
                { zip: '503', county: '花壇鄉' },
                { zip: '504', county: '秀水鄉' },
                { zip: '505', county: '鹿港鎮' },
                { zip: '506', county: '福興鄉' },
                { zip: '507', county: '線西鄉' },
                { zip: '508', county: '和美鎮' },
                { zip: '509', county: '伸港鄉' },
                { zip: '510', county: '員林鎮' },
                { zip: '511', county: '社頭鄉' },
                { zip: '512', county: '永靖鄉' },
                { zip: '513', county: '埔心鄉' },
                { zip: '514', county: '溪湖鎮' },
                { zip: '515', county: '大村鄉' },
                { zip: '516', county: '埔鹽鄉' },
                { zip: '520', county: '田中鎮' },
                { zip: '521', county: '北斗鎮' },
                { zip: '522', county: '田尾鄉' },
                { zip: '523', county: '埤頭鄉' },
                { zip: '524', county: '溪州鄉' },
                { zip: '525', county: '竹塘鄉' },
                { zip: '526', county: '二林鎮' },
                { zip: '527', county: '大城鄉' },
                { zip: '528', county: '芳苑鄉' },
                { zip: '530', county: '二水鄉' }
            ]
        },
        {
            city: '南投縣',
            contain: [
                { zip: '540', county: '南投市' },
                { zip: '541', county: '中寮鄉' },
                { zip: '542', county: '草屯鎮' },
                { zip: '544', county: '國姓鄉' },
                { zip: '545', county: '埔里鎮' },
                { zip: '546', county: '仁愛鄉' },
                { zip: '551', county: '名間鄉' },
                { zip: '552', county: '集集鎮' },
                { zip: '553', county: '水里鄉' },
                { zip: '555', county: '魚池鄉' },
                { zip: '556', county: '信義鄉' },
                { zip: '557', county: '竹山鎮' },
                { zip: '558', county: '鹿谷鄉' }
            ]
        },
        {
            city: '雲林縣',
            contain: [
                { zip: '630', county: '斗南鎮' },
                { zip: '631', county: '大埤鄉' },
                { zip: '632', county: '虎尾鎮' },
                { zip: '633', county: '土庫鎮' },
                { zip: '634', county: '褒忠鄉' },
                { zip: '635', county: '東勢鄉' },
                { zip: '637', county: '崙背鄉' },
                { zip: '638', county: '麥寮鄉' },
                { zip: '640', county: '斗六市' },
                { zip: '643', county: '林內鄉' },
                { zip: '646', county: '古坑鄉' },
                { zip: '647', county: '莿桐鄉' },
                { zip: '648', county: '西螺鎮' },
                { zip: '649', county: '二崙鄉' },
                { zip: '651', county: '北港鎮' },
                { zip: '652', county: '水林鄉' },
                { zip: '653', county: '口湖鄉' },
                { zip: '654', county: '四湖鄉' },
                { zip: '655', county: '元長鄉' }
            ]
        },
        {
            city: '嘉義市',
            contain: [
                { zip: '600', county: '嘉義市' }
            ]
        },
        {
            city: '嘉義縣',
            contain: [
                { zip: '602', county: '番路鄉' },
                { zip: '603', county: '梅山鄉' },
                { zip: '604', county: '竹崎鄉' },
                { zip: '605', county: '阿里山鄉' },
                { zip: '606', county: '中埔鄉' },
                { zip: '607', county: '大埔鄉' },
                { zip: '608', county: '水上鄉' },
                { zip: '611', county: '鹿草鄉' },
                { zip: '612', county: '太保市' },
                { zip: '613', county: '朴子市' },
                { zip: '614', county: '東石鄉' },
                { zip: '615', county: '六腳鄉' },
                { zip: '616', county: '新港鄉' },
                { zip: '621', county: '民雄鄉' },
                { zip: '622', county: '大林鎮' },
                { zip: '623', county: '溪口鄉' },
                { zip: '624', county: '義竹鄉' },
                { zip: '625', county: '布袋鎮' }
            ]
        },
        {
            city: '臺南市',
            contain: [
                { zip: '700', county: '中西區' },
                { zip: '701', county: '東區' },
                { zip: '702', county: '南區' },
                { zip: '704', county: '北區' },
                { zip: '708', county: '安平區' },
                { zip: '709', county: '安南區' },
                { zip: '710', county: '永康區' },
                { zip: '711', county: '歸仁區' },
                { zip: '712', county: '新化區' },
                { zip: '713', county: '左鎮區' },
                { zip: '714', county: '玉井區' },
                { zip: '715', county: '楠西區' },
                { zip: '716', county: '南化區' },
                { zip: '717', county: '仁德區' },
                { zip: '718', county: '關廟區' },
                { zip: '719', county: '龍崎區' },
                { zip: '720', county: '官田區' },
                { zip: '721', county: '麻豆區' },
                { zip: '722', county: '佳里區' },
                { zip: '723', county: '西港區' },
                { zip: '724', county: '七股區' },
                { zip: '725', county: '將軍區' },
                { zip: '726', county: '學甲區' },
                { zip: '727', county: '北門區' },
                { zip: '730', county: '新營區' },
                { zip: '731', county: '後壁區' },
                { zip: '732', county: '白河區' },
                { zip: '733', county: '東山區' },
                { zip: '734', county: '六甲區' },
                { zip: '735', county: '下營區' },
                { zip: '736', county: '柳營區' },
                { zip: '737', county: '鹽水區' },
                { zip: '741', county: '善化區' },
                { zip: '742', county: '大內區' },
                { zip: '743', county: '山上區' },
                { zip: '744', county: '新市區' },
                { zip: '745', county: '安定區' }
            ]
        },
        {
            city: '高雄市',
            contain: [
                { zip: '800', county: '新興區' },
                { zip: '801', county: '前金區' },
                { zip: '802', county: '苓雅區' },
                { zip: '803', county: '鹽埕區' },
                { zip: '804', county: '鼓山區' },
                { zip: '805', county: '旗津區' },
                { zip: '806', county: '前鎮區' },
                { zip: '807', county: '三民區' },
                { zip: '811', county: '楠梓區' },
                { zip: '812', county: '小港區' },
                { zip: '813', county: '左營區' },
                { zip: '814', county: '仁武區' },
                { zip: '815', county: '大社區' },
                { zip: '820', county: '岡山區' },
                { zip: '821', county: '路竹區' },
                { zip: '822', county: '阿蓮區' },
                { zip: '823', county: '田寮區' },
                { zip: '824', county: '燕巢區' },
                { zip: '825', county: '橋頭區' },
                { zip: '826', county: '梓官區' },
                { zip: '827', county: '彌陀區' },
                { zip: '828', county: '永安區' },
                { zip: '829', county: '湖內區' },
                { zip: '830', county: '鳳山區' },
                { zip: '831', county: '大寮區' },
                { zip: '832', county: '林園區' },
                { zip: '833', county: '鳥松區' },
                { zip: '840', county: '大樹區' },
                { zip: '842', county: '旗山區' },
                { zip: '843', county: '美濃區' },
                { zip: '844', county: '六龜區' },
                { zip: '845', county: '內門區' },
                { zip: '846', county: '杉林區' },
                { zip: '847', county: '甲仙區' },
                { zip: '848', county: '桃源區' },
                { zip: '849', county: '那瑪夏區' },
                { zip: '851', county: '茂林區' },
                { zip: '852', county: '茄萣區' }
            ]
        },
        {
            city: '屏東縣',
            contain: [
                { zip: '900', county: '屏東市' },
                { zip: '901', county: '三地門鄉' },
                { zip: '902', county: '霧臺鄉' },
                { zip: '903', county: '瑪家鄉' },
                { zip: '904', county: '九如鄉' },
                { zip: '905', county: '里港鄉' },
                { zip: '906', county: '高樹鄉' },
                { zip: '907', county: '鹽埔鄉' },
                { zip: '908', county: '長治鄉' },
                { zip: '909', county: '麟洛鄉' },
                { zip: '911', county: '竹田鄉' },
                { zip: '912', county: '內埔鄉' },
                { zip: '913', county: '萬丹鄉' },
                { zip: '920', county: '潮州鎮' },
                { zip: '921', county: '泰武鄉' },
                { zip: '922', county: '來義鄉' },
                { zip: '923', county: '萬巒鄉' },
                { zip: '924', county: '崁頂鄉' },
                { zip: '925', county: '新埤鄉' },
                { zip: '926', county: '南州鄉' },
                { zip: '927', county: '林邊鄉' },
                { zip: '928', county: '東港鎮' },
                { zip: '929', county: '琉球鄉' },
                { zip: '931', county: '佳冬鄉' },
                { zip: '932', county: '新園鄉' },
                { zip: '940', county: '枋寮鄉' },
                { zip: '941', county: '枋山鄉' },
                { zip: '942', county: '春日鄉' },
                { zip: '943', county: '獅子鄉' },
                { zip: '944', county: '車城鄉' },
                { zip: '945', county: '牡丹鄉' },
                { zip: '946', county: '恆春鎮' },
                { zip: '947', county: '滿州鄉' }
            ]
        },
        {
            city: '宜蘭縣',
            contain: [
                { zip: '260', county: '宜蘭市' },
                { zip: '261', county: '頭城鎮' },
                { zip: '262', county: '礁溪鄉' },
                { zip: '263', county: '壯圍鄉' },
                { zip: '264', county: '員山鄉' },
                { zip: '265', county: '羅東鎮' },
                { zip: '266', county: '三星鄉' },
                { zip: '267', county: '大同鄉' },
                { zip: '268', county: '五結鄉' },
                { zip: '269', county: '冬山鄉' },
                { zip: '270', county: '蘇澳鎮' },
                { zip: '272', county: '南澳鄉' }
            ]
        },
        {
            city: '花蓮縣',
            contain: [
                { zip: '970', county: '花蓮市' },
                { zip: '971', county: '新城鄉' },
                { zip: '972', county: '秀林鄉' },
                { zip: '973', county: '吉安鄉' },
                { zip: '974', county: '壽豐鄉' },
                { zip: '975', county: '鳳林鎮' },
                { zip: '976', county: '光復鄉' },
                { zip: '977', county: '豐濱鄉' },
                { zip: '978', county: '瑞穗鄉' },
                { zip: '979', county: '萬榮鄉' },
                { zip: '981', county: '玉里鎮' },
                { zip: '982', county: '卓溪鄉' },
                { zip: '983', county: '富里鄉' }
            ]
        },
        {
            city: '臺東縣',
            contain: [
                { zip: '950', county: '台東市' },
                { zip: '951', county: '綠島鄉' },
                { zip: '952', county: '蘭嶼鄉' },
                { zip: '953', county: '延平鄉' },
                { zip: '954', county: '卑南鄉' },
                { zip: '955', county: '鹿野鄉' },
                { zip: '956', county: '關山鎮' },
                { zip: '957', county: '海端鄉' },
                { zip: '958', county: '池上鄉' },
                { zip: '959', county: '東河鄉' },
                { zip: '961', county: '成功鎮' },
                { zip: '962', county: '長濱鄉' },
                { zip: '963', county: '太麻里鄉' },
                { zip: '964', county: '金峰鄉' },
                { zip: '965', county: '大武鄉' },
                { zip: '966', county: '達仁鄉' }
            ]
        },
        {
            city: '澎湖縣',
            contain: [
                { zip: '880', county: '馬公市' },
                { zip: '881', county: '西嶼鄉' },
                { zip: '882', county: '望安鄉' },
                { zip: '883', county: '七美鄉' },
                { zip: '884', county: '白沙鄉' },
                { zip: '885', county: '湖西鄉' }
            ]
        },
        {
            city: '金門縣',
            contain: [
                { zip: '890', county: '金沙鎮' },
                { zip: '891', county: '金湖鎮' },
                { zip: '892', county: '金寧鄉' },
                { zip: '893', county: '金城鎮' },
                { zip: '894', county: '烈嶼鄉' },
                { zip: '896', county: '烏坵鄉' }
            ]
        },
        {
            city: '連江縣',
            contain: [
                { zip: '209', county: '南竿鄉' },
                { zip: '210', county: '北竿鄉' },
                { zip: '211', county: '莒光鄉' },
                { zip: '212', county: '東引鄉' }
            ]
        },
    ]