var lang: LangStruct = {
    web_title: 'RaLa',
    my_name: 'I am Jerry',
    add: 'Add New',
    done: 'Done',
    next_step: 'NextStep',
    submitorder: '送出需求單',
    submit_copy: '確定複製',
    save: 'Save',
    save_define: '確定送出',
    recycle: '收回',
    recycle_order: '收回需求單',
    fall_back: '退回',
    fallback_order: '退回需求單',
    tempdraft: '暫存草稿',
    tempsave: '暫存',
    cancel: 'Cancel',
    cancel_return: 'Cancel / Return',
    cancel_sure: '是否要取消?',
    modify: 'Modify',
    edit: 'edit',
    delete: 'Delete',
    select: 'Select',
    view: 'View',
    delete_sure: '確定是否刪除?',
    recycle_sure: '確定回收此訂單?',
    fallback_sure: '確定退回此訂單?',
    logout_sure: '確定登出此系統?',
    leave_sure: '是否要離開?',
    print: 'Print',
    return: '回上頁',
    return_list: '回到列表',
    after_insert: '請新增完後再上傳',
    report: '報表',
    mk_loading: '資料載入中...',
    mk_reading: '資料讀取中...',
    mk_updating: '資料更新中...',
    mk_login: '登錄中...',
    mk_searching: '查詢中...',
    option_blank: '請選擇',
    fi_insert: '新增完成',
    fi_update: '修改完成',
    fi_copyto: '複製完成',
    fi_delete: '刪除完成',
    fi_deliver: '提出申報完成',
    prve_page: '上一頁',
    next_page: '下一頁',
    first_page: '第一頁',
    last_page: '最後頁',
    search: '查詢',
    close: '×',
    clear: '清除重填',
    start_search: '開始搜尋',
    detail: '明細',
    thankforbuy: 'Thank you for buying',
    err_selprod: '請選擇至少一項品項',
    err_prodqty:'所有品項均需登打數量'
}